### ISSUE TITLE
Is a full ROM really necessary?

### ISSUE THREAD

**Issue by devhij** [maruos/maruos#96] opened 2018-09-09 18:37 UTC
I think the thing that makes Maru OS really difficult to develop for and to gain more adoption is being a full ROM.

Couldn't it work as an app? Of course then some features would be difficult or just impossible to implement, perhaps with rooting, but honestly going to the Play Store and being able to install it as a plain application would be very, very nice.

Why not?

**Comment by pdsouza** [comment] 2018-09-09 19:51
Duplicate of https://github.com/maruos/maruos/issues/46.

I agree 100%--I would *love* not having to maintain a full ROM for Maru. But it's necessary right now for the level of integration that Maru offers. See above for details why, but in short, it would be very difficult or impossible as far as I know to do simultaneous and independent interaction with the desktop over HDMI and phone at the same time, clean desktop isolation for running systemd, hardware passthrough to the desktop, low-latency desktop interaction, etc.

One thing I have considered for a long time is tinkering with a "Maru Lite" app to see how far we can take the Maru experience via just an app. Perhaps there are ways of making trade-offs to work around the issues above to get Maru to more users. My gut tells me the experience wouldn't be quite as compelling, but it may be good enough for casual users. Is this something you'd be interested in?

**Comment by sirocyl** [comment] 2019-03-08 06:14
One thing I'd be interested in, is the possibility of including kernel/platform level enhancements to a base ROM that is otherwise feature-indistinguishable, much like the Lineage builds which support microG - and by making the changes more generic, enable building a "Lineage" ROM for each phone which has Maru capabilities. From there, Maru could be enabled by a flash-on ZIP, or an app which communicates to a sort of "Maru API" exposed to Android (behind a permissions check, of course), for controlling Maru.

**Comment by 4223** [comment] 2019-03-08 14:08
...a "Maru Lite" app would be really nice. For most use cases, this could indeed be sufficient..

**Comment by utzcoz** [comment] 2021-12-07 13:43
If anyone has interested in this problem, you can left your words at https://github.com/maruos/maruos/issues/46. Also, there is an issue for migrating MaruOS's functions to a single app, you can check https://github.com/maruos/maruos/issues/99 if you have interested in. I will close it with duplicated reason, and feel free to reopen it if you have problem.

**Closed by utzcoz** 2021-12-07 13:43 UTC

**Comment by twaik** [comment] 2022-10-06 15:17
@utzcoz I think it can work, but a bit other way. We can use [KVM](https://lwn.net/Articles/836693/). It will consume more resources on device but will work on more devices and it will likely be more stable. There are a lot of instruments that can help to make it work, i.e. `pulseaudio` is accessible from network (we already have ported it to bionic), hardware acceleration using `virtio-gpu-3d`+modified `virglrenderer` (see [this](https://cs.android.com/android/platform/superproject/+/android-10.0.0_r1:device/generic/opengl-transport/host/libs/virglrenderer/)), input can be implemented with something like x2x.
Porting KVM to existing kernel as module is much easier than patching kernel to support all Desktop kernel features.

**Comment by utzcoz** [comment] 2022-10-06 15:19
@twaik IMO, we can leverage pKVM from Android 13. It's integrated into AOSP default from Android 13 for security and special case usage.

**Comment by utzcoz** [comment] 2022-10-06 15:23
@twaik I think it will be difficult. And I have discussed with @pdsouza to speed up MaruOS' version and release speed to catch up with the official version, and we can try it when we have MaruOS based on Android 13.
