### ISSUE TITLE
about the cpu （kernel）working mode 300Mhz-2265Mhz 25% Used is the BUG?

### ISSUE THREAD

**Issue by liuki342166** [maruos/maruos#58] opened 2016-12-18 11:56 UTC
When I'm still on the screen the cpu0 working 300Mhz，cpu1-3 is offline，This is a very good design, very power-saving.
<img src='http://p1.bpimg.com/581650/2d1d01be0333b846.png'>

When I open an app or play a game the cpu working 2265Mhz # , # **but the CPU Load is very few ,Games and applications run very slowly**
<img src='http://i1.piimg.com/581650/13dc9538a1ea0f14.png'>
<img src='http://i1.piimg.com/581650/7905d40504fb13b0.png'>
It's hard to accept.

I try to flash the kernel , So as to solve the problem ,But there is a new problem.
**# Maru desktop is not working !!!**
Can you provide a new kernel to improve the CPU capacity % problem ?
Very thank!!!!

**Comment by chevdroid** [comment] 2017-01-04 10:30
Hi liuki,

Are you're screenshots from debian (it looks like for me) or in android?
How does the RAM & I/O usage look in the same time? For example if RAM is used 100% and/or I/O it is possible that the CPU can't do more things in the moment (no free RAM or iowait) The entire system needs to be monitored not just CPU.

For your flashed kernel, did you used a stock, 3rd party kernel? If yes, thats why Maru OS is not working, Maru OS needs special flags set in the kernel to work, stock and 3rd party kernels don't have these set. You have to use the kernel included in Maru OS.

Hope that helps somewhat.

**Comment by liuki342166** [comment] 2017-01-04 10:53
thanks you chevdroid 

first my system is maru os , my desktop is can works, kernel is maru kernel, not 3rd part kernel,

Now my question is  properly done  cpu1,cpu2,cpu3, why not Full load work?  is only 0%... 

only Install App mode  cpu1, Cpu2,cpu3 can Full work....

Is this  maru kernel  question?

Thank you for your answer. @chevdroid

**Comment by chevdroid** [comment] 2017-01-04 14:00
So you just flashed the maru os kernel again, to solve your "issue" ? And then maru desktop didn't work anymore, or is it now working again? If it is not working, try to flash Maru OS (System, Kernel, Recovery) again.

And just for clarification, CPU 0 is using 0-100% and CPU1, CPU2 and CPU3 only 0%, when running games or other heavy load tasks? Are you running those in maru desktop or in "normal" mobile mode?
Also did you check how much RAM was used or if you had a high iowait? Which would mean that your CPU was waiting for i/o or ram.

I think it has more to do with what & where it was running, and not a bug in the kernel.

**Comment by liuki342166** [comment] 2017-01-04 15:27
thank you 

i system is Maru os , i diden't flashed 3rd kernel ..... 

i just want to say the Maru os kernel is Not working hardly........ wow....
other 3rd kernel . is  work hardly..... 

about the kernel  Cpu0 is using 0-100％,,,,, Do you have the same situation as me?

did you using the 'PerMon' app  to testing cpu0 working mode in the Maru os ? just Just monitor, do not use the phone  if you can.

Thak you your answer. @chevdroid

**Comment by curiousercreative** [comment] 2017-04-08 15:07
I investigated this a bit as well and it seems that the guest Debian OS has full access to the host OS CPU and memory resources and can harness all four cores of the Nexus 5. Here's how I tested:
1. Install `sysbench` (a benchmarking package) on Debian: `sudo apt-get install sysbench`
1. Open a second window in Debian and run `top`
1. In the first window, run a multi-threaded benchmark (4 threads here): `sysbench --test=cpu --num-threads=4 run`
1. In the second window with `top` running, observe the CPU usage. For me, it'd be between 300-400% indicating all four cores were active.
1. In the first window, run a single-threaded benchmark and observe the difference: `sysbench --test=cpu run`. In `top`, I see 100% CPU activity, but in your monitoring application it will very likely be 25% @chevdroid .
1. Additionally, if you have a CPU core monitoring application (I used [Kernel Aduitor](https://play.google.com/store/apps/details?id=com.grarak.kerneladiutor)) installed on your host Android OS, you can also observe each of the cores working diligently.

I took it one step further and on the host Android OS, I ran `top` and from there you can see the CPU and memory resources are very closely mirrored to the guest Debian OS `top`. The two don't seem to be aware of each other's processes, but they do share resource activity monitors. Very cool!

The benchmarking was borrowed from this [post](http://askubuntu.com/questions/634513/cpu-benchmarking-utility-for-linux#answer-634516).

**Comment by curiousercreative** [comment] 2017-05-09 03:12
@liuki342166 I keep thinking back to this thread and I think I may have misrepresented my results. I believe I had modified my kernel settings to disable cpu hotplugging prior to running this test. The stock kernel has cpu hotplugging enabled which switches cpu cores on and off based on cpu load. This hotplugging and perhaps running the phone without being plugged into power may produce a situation where the guest OS can only utilize the single core that is powered on. If you are experiencing a similar problem on Nexus 5, you're welcome to build and/or flash this fork of Franco's kernel that seems to work fully with MaruOS: https://groups.google.com/forum/#!topic/maru-os/TAEGbd27U68.

**Comment by Tiima** [comment] 2017-05-18 14:45
Might have bumped to same issue. I yesterday installed maru to nexus 5 (wohoo so simple, i like it btw)
I ssh to maru and run `sysbench --test=cpu --cpu-max-prime=20000 --num-threads=4 run`
and on another ssh console i observe cpu load with `htop`  what will show this:

`CPU   PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
  1   380 maru       20   0  6656  1096   812 S 97.4  0.1  0:09.08 sysbench --test cpu --cpu-max-prime 20000 --num-threads 4 run
  1   384 maru       20   0  6656  1096   812 R 24.1  0.1  0:02.26 sysbench --test cpu --cpu-max-prime 20000 --num-threads 4 run
  1   383 maru       20   0  6656  1096   812 R 24.4  0.1  0:02.26 sysbench --test cpu --cpu-max-prime 20000 --num-threads 4 run
  1   382 maru       20   0  6656  1096   812 R 24.4  0.1  0:02.26 sysbench --test cpu --cpu-max-prime 20000 --num-threads 4 run
  1   381 maru       20   0  6656  1096   812 R 24.4  0.1  0:02.26 sysbench --test cpu --cpu-max-prime 20000 --num-threads 4 run`

All treads are running in same core.
Haven't yet installed any program on android side to look processor load per core there

**Comment by pdsouza** [comment] 2017-06-12 01:08
So I was wondering what the heck was going on with this and I took a look last night...

### Short story

You guys are right that desktop threads are only scheduled on the the first CPU--I am embarassed that I did not notice this sooner! Thank you guys for all the detailed feedback that helped me diagnose this issue!

I have verified and already pushed a fix that will be available in the next release, see commit message for a detailed explanation: https://github.com/maruos/vendor_maruos/commit/364fd09bb613699645d22030dd00102291f738bf.

After unconstraining the desktop, multi-threaded performance is significantly improved and the desktop feels much smoother when running multiple processes!

### Long story

I never explicitly set any resource limitations on the desktop container other than device passthrough so I just assumed that Android's scheduling and hotplugging (there is a custom qualcomm daemon /system/bin/mpdecision that does frequent hotplugging of cores for optimization) was resulting in a condition where a single core boosted to the maximum frequency would offer better performance than all four cores running at medium/low frequencies due to thermal costs of having more cores running--thus resulting in these reports. 

Since a bunch of you have been bringing this up though I wanted to make sure my assumption was correct so I took a closer look...and I discovered that to my utter astonishment, all four cores were online, i.e. cpu1,2,3 were hungry and able to take on work but were being starved for some unknown reason! 

So I lifted the hood and started poking around. I tried to pin a process to a core other than cpu0 by setting the CPU affinity of a process with `taskset` and got -EINVAL when I tried to set the affinity to anything other than cpu0! With a little `strace` digging, I discovered that `taskset` calls the `sched_setaffinity` system call, which returns -EINVAL when either the specified process is 1) not available on the system or 2) restricted via the [cpuset](http://man7.org/linux/man-pages/man7/cpuset.7.html) kernel resource controller. I had already established that the other cores were online, so I wondered if LXC was setting up unexpected cpuset limits on the container even though I never explicitly set any cpuset limits myself. 

It turns out that LXC by default sets up all resource controllers available on the system if a global configuration file is not present that explicitly lists which resource controllers should be set up. Thus, LXC would set up cpusets for the desktop container. The first time you start the desktop, LXC would just copy over the default cpuset limits (all online cores)--this is correct and makes total sense...EXCEPT when you have a system where cores are hotplugged frequently like with the Nexus 5 and /system/bin/mpdecision! What was happening, was that whenever the system idled, mpdecision would unplug all cores except cpu0, forcing the root cpuset to be limited to just cpu0, and thus forcing any of it's child cpusets including LXC, to be squeezed down to cpu0--this is just an artifact of the property that cpusets must be subsets of the root cpuset of course. When you start actively using the desktop (e.g. running multi-threaded `sysbench`) mpdecision would dutifully plug in the rest of the cores, but the LXC cpuset would not be updated to reflect this and would stay stuck at 0. 

The net effect of all this is that Android processes (constrained under the root cpuset) would be able to make use of all online cores at anytime regardless of hotplugging, but desktop container processes (constrained under the LXC child cpuset) would be stuck on cpu0!

I fixed this temporarily by setting the cpuset limits to be all cores while the system was under load, but the limits would revert back to just cpu0 after the system idled as explained above. The permanent fix is telling LXC not to use cpusets at all.

### How to play with this stuff yourself

To tie everything up together, I have a screencast showing you all this stuff in real-time and how you can temporarily enable all cores when the system is loaded--thought it was pretty cool and I learnt a lot just debugging this so wanted to share in case anyone else is interested: https://asciinema.org/a/124345.

**Comment by pdsouza** [comment] 2019-02-26 19:37
This fix is available in our [0.6 builds](https://github.com/maruos/builds/releases) and is very stable. I think you'll enjoy the multi-process performance bump! (Sincere apologies for taking so long to release the official builds for this.)

**Comment by pdsouza** [comment] 2019-03-06 21:54
Closing this now that 0.6 has been released.

**Closed by pdsouza** 2019-03-06 21:54 UTC

**Comment by stealthybox** [comment] 2019-06-19 02:31
@pdsouza: by the way, the asymmetric hotplug behavior is a bug with v1 cgroups.

This is fixed in newer kernels with `cpuset.cpus` and `cpuset.cpus.effective` using cgroup v2:
https://www.kernel.org/doc/html/latest/admin-guide/cgroup-v2.html#cpuset-interface-files

> #### cpuset.cpus
> 
> A read-write multiple values file which exists on non-root cpuset-enabled cgroups.
> 
> It lists the requested CPUs to be used by tasks within this cgroup. The actual list of CPUs to be granted, however, is subjected to constraints imposed by its parent and can differ from the requested CPUs.
> 
> The CPU numbers are comma-separated numbers or ranges. For example:
> 
>         # cat cpuset.cpus 0-4,6,8-10
> 
> An empty value indicates that the cgroup is using the same setting as the nearest cgroup ancestor with a non-empty “cpuset.cpus” or all the available CPUs if none is found.
> 
> The value of “cpuset.cpus” stays constant until the next update and won’t be affected by any CPU hotplug events.
> #### cpuset.cpus.effective
> 
> A read-only multiple values file which exists on all cpuset-enabled cgroups.
> 
> It lists the onlined CPUs that are actually granted to this cgroup by its parent. These CPUs are allowed to be used by tasks within the current cgroup.
> 
> If “cpuset.cpus” is empty, the “cpuset.cpus.effective” file shows all the CPUs from the parent cgroup that can be available to be used by this cgroup. Otherwise, it should be a subset of “cpuset.cpus” unless none of the CPUs listed in “cpuset.cpus” can be granted. In this case, it will be treated just like an empty “cpuset.cpus”.
> 
> Its value will be affected by CPU hotplug events.
> 

This may not be a necessary config for newer devices.
:)
