### ISSUE TITLE
Physical keyboard and mouse

### ISSUE THREAD

**Issue by danielartdiaz** [maruos/maruos#69] opened 2017-04-01 20:17 UTC
Ive tried to install a wireless keyboard and mouse via bluetooth, and when i connect it, it doesn't work. I've tried connecting it to my google pixel and it worked just fine. is there anyway to fix this issue on the nexus 7 running the latest build of maru?

Update: ive read some of the other forums and supposedly it works on the desktop side. i want to know is there anyway to get this on the android side?

**Comment by pdsouza** [comment] 2017-04-01 20:20
I'm assuming you are talking about BT keyboard and mouse usage on Android right? BT input devices are reserved for use only within Maru Desktop by design. This is a well known issue and requires more work for a robust solution, it's been on my list for awhile: https://github.com/maruos/maruos/issues/12.

**Comment by curiousercreative** [comment] 2017-04-22 17:10
@pdsouza can this be closed as a duplicate?

**Comment by pdsouza** [comment] 2017-04-23 00:41
@curiousercreative Thank you, closing!

**Closed by pdsouza** 2017-04-23 00:41 UTC
Labels: duplicate
