### ISSUE TITLE
Maru os not working

### ISSUE THREAD

**Issue by amao1** [maruos/maruos#62] opened 2017-02-24 01:54 UTC
I downloaded maro, but it failed to start when I connected it to my display. I tried restarting the device as well as performing a factory reset, but that didn't help either. Any help is appreciated.

**Comment by pdsouza** [comment] 2017-02-24 02:06
Are you using a SlimPort cable? 
What does `Settings > Dashboard` show when you connect to your display?
Have you encrypted your device? There is an open issue with encryption on v0.3 and lower: https://github.com/maruos/maruos/issues/17

You can send a bug report with all of your logs so I can look through them

**Comment by amao1** [comment] 2017-02-24 02:39
Thanks for replying so soon, yes I am using the recommended cablematters cable, when I try and connect to a display, it says "Maru os failed to start" almost immediately after I try and start it.

This is my bug report 
 https://drive.google.com/file/d/0B1Kg2IHp7g1oSXI0Zy1rc3BfaWM/view?usp=drivesdk

**Comment by pdsouza** [comment] 2017-02-24 02:50
Thanks for the bug report, but it doesn't look like I see any logs related to the desktop failure? 

Can you make sure that you reproduce the bug by attaching the SlimPort cable to your TV, waiting for the error to show up in `Settings > Dashboard`, and then sending me the bug report?

**Comment by amao1** [comment] 2017-02-24 03:42
Sorry, here is the new bug report
https://drive.google.com/file/d/0B1Kg2IHp7g1obEowdU53RmhYZXc/view?usp=drivesdk

**Comment by pdsouza** [comment] 2017-02-24 04:03
```
...
02-23 22:37:01.227   783   801 I DisplayManagerService: Display device added: DisplayDeviceInfo{"HDMI Screen": uniqueId="local:1", 640 x 480, modeId 2, defaultModeId 2, supportedModes [{id=2, width=640, height=480, fps=60.000004}], colorTransformId 2, defaultColorTransformId 2, supportedColorTransforms [{id=2, colorTransform=0}], density 142, 142.0 x 142.0 dpi, appVsyncOff 7500000, presDeadline 12666666, touch EXTERNAL, rotation 0, type HDMI, state UNKNOWN, FLAG_SECURE, FLAG_SUPPORTS_PROTECTED_BUFFERS, FLAG_PRESENTATION, FLAG_DEFAULT_EXTERNAL_DISPLAY}
02-23 22:37:01.228   193   193 D SurfaceFlinger: Set power mode=2, type=1 flinger=0xb6aa4000
02-23 22:37:01.228   193   193 D qdhwcomposer: hwc_blank: Unblanking display: 1
02-23 22:37:01.228   193   193 D qdhwcomposer: hwc_blank: Done unblanking display: 1
02-23 22:37:01.229   783   801 I DisplayManagerService: Display device changed state: "HDMI Screen", ON
02-23 22:37:01.230   783   798 I PerspectiveService: HDMI display added, scheduling desktop start...
02-23 22:37:01.230   783   798 D PerspectiveService: mDesktopState: STOPPED -> STARTING
02-23 22:37:01.232   213   230 D perspectived: running start()...
02-23 22:37:01.253   783   879 I InputReader: Reconfiguring input devices.  changes=0x00000004
02-23 22:37:01.419   213   230 D perspectived: liblxc returned false for start, possible false positive...
02-23 22:37:01.420   213   230 E perspectived: failed to start desktop
02-23 22:37:01.420   783   798 E PerspectiveService: nativeStart failed
02-23 22:37:01.420   783   798 D PerspectiveService: mDesktopState: STARTING -> STOPPED
...
```

OK, so looks like the system is detecting your display fine (although it is very low res 640x480) and is trying to start up the desktop, but the start is failing.

This really looks to me like it could be caused by a semi-rare race condition where your desktop files are not being properly set up before the start is called on your very first boot. Did you try to connect to your display immediately after the phone booted up with Maru OS the first time? This is usually fixed via a re-install or a factory reset when it happens.

Did you use the installer or TWRP to install Maru OS? If you used TWRP, we can do a selective delete of the `/data/maru/` directory via TWRP's file manager and then reboot to get everything synced over properly. You may need to wait 5 minutes or so after the first boot before trying to connect to your display.

**Comment by amao1** [comment] 2017-02-24 04:09
OK thanks, I installed Maru using their installer on the website, and I waited a couple days before attempting to connect to a display. Do you have any idea why the resolution is so low? I will probably reinstall tomorrow, so I will get back to you when it's finished. Thanks.

**Comment by pdsouza** [comment] 2017-02-24 04:14
Not sure what's going on with your display, that resolution is very strange. Do you by chance have the USB charging port connected to power when you plug your device to the cable? Sometimes I have noticed that this messes up the resolution the device reads from the display, so it defaults to the safe VGA resolution of 640x480. I suggest unplugging the power port, connecting the device and verifying the resolution is normal, and then connecting the cable's charging port to power. Displays are very idiosyncratic and finicky sometimes unfortunately...

And yes, sounds good, please let me know how the re-install goes! I hope we can get this fixed quickly for you!

**Comment by amao1** [comment] 2017-02-27 00:49
OK, sorry for the delay, I was preoccupied. I am currently having trouble uninstalling Maru, whenever I past the directory it lists stuff such as 
"adb not recognized as an internal or external command, operable program or batch file."
"Flash-all is not recognized as an internal or external command, operable program or batch file." 
I downloaded the 6.01 (M4B30Z Dec. 2016) file and only pasted the unzipped image-hammerhead-m4b30z file.

**Comment by pdsouza** [comment] 2017-02-27 22:16
@chevdroid is right that you will need adb in your path to run the uninstaller script, please use his links to obtain the adb/fastboot binaries if you need them. Please also make sure that you paste all the files in the factory M4B30Z zip you downloaded, not just the image-hammerhead-* file.

**If your goal is to just re-install Maru OS though**, you can skip the uninstall and just run the installer again since it will factory reset your device anyway.

Feel free to let us know if you need step-by-step instructions, we are happy to help!

**Comment by pdsouza** [comment] 2019-10-17 13:50
Closing this due to inactivity.

**Closed by pdsouza** 2019-10-17 13:50 UTC
