### ISSUE TITLE
Wifi Hotspot Error

### ISSUE THREAD

**Issue by clxt** [maruos/maruos#115] opened 2019-07-26 08:27 UTC
Hi, I just installed Maru OS 0.6.6 on my Nexus 5 (hammerhead).
When I try to enable wifi hotspot I get **Error**.
I tried to reset wifi and bluetooth (in System>reset options) but it didn't fix it, even after reboot.

Hotspot through USB doesn't work either (unable to slide the button), nor through bluetooth (my computer doesn't detect it)

Thanks a lot!

**Comment by AbdoQ** [comment] 2019-08-20 14:43
Same problem here!

**Comment by pdsouza** [comment] 2019-08-20 22:28
OK, thanks for the report guys.

I am able to use Wi-Fi hotspot on N5X (bullhead) just fine, so it is likely that this is an issue with our vendor blobs for hammerhead. I'll take a look.

**Comment by pdsouza** [comment] 2019-08-20 23:10
Just confirmed that I am getting the same "Error" message after enabling Wi-Fi Hotspot when mobile data is enabled on a fresh build. I see errors related to WiFiHAL / WiFiVendorHAL in logcat.

**Comment by pdsouza** [comment] 2019-08-22 02:33
Alrighty, figured out it was an issue with missing some networking functionality in the kernel! See https://github.com/maruos/android_kernel_hammerhead/commit/733c76301527870e17fcbe22fe96d968a1285559.

I tested with a fresh build with the new kernel config and can confirm that:
 - Wi-Fi Hotspot works
 - Bluetooth tethering works

I wasn't able to test USB tethering on my Mac since it's missing some drivers for that but please let me know if it works for you. Note that you need to connect a USB cable to your PC first for the "USB tethering" toggle switch to become selectable under Network Settings.

Thanks again for bringing this to my attention. This fix will be out in our next release.

**Comment by pdsouza** [comment] 2019-09-05 23:40
@clxt @AbdoQ v0.6.7 is now available with this fix. Please upgrade!

Find the latest downloads here: https://maruos.com/downloads/

**Comment by pdsouza** [comment] 2019-09-08 16:50
Closing - please feel free to re-open if you are still having issues with your hotspot.

**Closed by pdsouza** 2019-09-08 16:51 UTC
Labels: device/hammerhead
