### ISSUE TITLE
NFC doesn't work on Nexus 5

### ISSUE THREAD

**Issue by ec1oud** [maruos/maruos#103] opened 2019-02-16 11:03 UTC
I need it to use Password Store with my Yubikey.  This works fine on my Moto Z.  Also tried another NFC card with NFC Reader (from F-Droid); the phone just doesn't react to the card anywhere that I've put it in contact along the backside or around the edges of the front.

**Comment by TMartinPPC** [comment] 2019-02-16 15:42
I don't think the Nexus 5 has NFC.

**Comment by ec1oud** [comment] 2019-02-16 21:51
https://www.gsmarena.com/lg_nexus_5-5705.php says it does
https://www.reddit.com/r/Nexus5/comments/4prj1p/nfc_not_working_anymore/ says it could be a hardware issue
but does it usually work with Maru?

**Comment by pdsouza** [comment] 2019-02-18 05:00
Hey @ec1oud, I'm the maintainer for the N5. I've never actually used NFC on my Nexus 5 unfortunately and I don't have NFC hardware to verify myself so I don't know whether this is a hardware issue or not.

The best way to check if it's a hardware issue is to take a backup and flash the factory image and confirm if NFC works on the factory image. If it does, the issue is with Maru and I'll be happy to investigate further and figure out what we're missing in our image. Sorry for the hassle!

**Comment by PifPof73** [comment] 2019-03-18 15:14
> 
> 
> I don't think the Nexus 5 has NFC.

I can confirm that Nexus 5 does have NFC - I used it with Google android and Lineage - OS 14 (Android 7.2).

**Comment by PifPof73** [comment] 2019-09-09 06:29
Hi,
NFC is working under maru OS 0.66 and 0.67 on Nexus5 (hammerhead).
I use the "card emulator pro" and the "NFC Tools PRO" - App for testing.
I read out my credit card and EC card and some NFC tags from customer cards.
I did not test writing (as I don't have a writable NFC tag).
I think issue could be closed.
Regards,
PifPof73

**Comment by pdsouza** [comment] 2019-09-09 13:55
@PifPof73 Thanks for confirming NFC works on 0.6! Closing.

**Closed by pdsouza** 2019-09-09 13:55 UTC
Labels: device/hammerhead
